name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: mcp
        run: ./bun ci
      - name: Run ESLint
        working-directory: mcp
        run: ./bun run lint
      - name: Run Prettier
        working-directory: mcp
        run: ./bun run prettier:check
      - name: Run Type Check
        working-directory: mcp
        run: ./bun run typecheck
