name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: non-prod

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: mcp
        run: ./bun ci
      - name: Run Biome Linter
        working-directory: mcp
        run: ./bun run lint
      - name: Run Type Check
        working-directory: mcp
        run: ./bun run typecheck
